# Generated by Django 4.2.6 on 2023-10-11 16:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", django_countries.fields.CountryField(max_length=2)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=100)),
                ("house_number", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Mail",
                "verbose_name_plural": "Mails",
                "db_table": "Mails",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
                "db_table": "Staff",
            },
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies_details.address",
                        verbose_name="Address ID",
                    ),
                ),
                (
                    "mail_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies_details.mail",
                        verbose_name="Mail ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacts",
                "verbose_name_plural": "Contacts",
                "db_table": "Contacts",
            },
        ),
    ]
